// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_FNqCEggu4zET39NuxaDU780qSjOZjc',
    appId: '1:575393981150:web:ced4b2a4e381b1a311984f',
    messagingSenderId: '575393981150',
    projectId: 'instagram-a8f7a',
    authDomain: 'instagram-a8f7a.firebaseapp.com',
    storageBucket: 'instagram-a8f7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUvlLqT3zacuy5GZUt2Hf3rwlW1s0r3g',
    appId: '1:575393981150:android:9231f103dbb4a83f11984f',
    messagingSenderId: '575393981150',
    projectId: 'instagram-a8f7a',
    storageBucket: 'instagram-a8f7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFUJGeup29QL55jpGEyBld3mLP6eR9Qc',
    appId: '1:575393981150:ios:ed691d742ddffdc811984f',
    messagingSenderId: '575393981150',
    projectId: 'instagram-a8f7a',
    storageBucket: 'instagram-a8f7a.appspot.com',
    iosBundleId: 'com.example.instagramAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFUJGeup29QL55jpGEyBld3mLP6eR9Qc',
    appId: '1:575393981150:ios:e13dd4bbb741f2da11984f',
    messagingSenderId: '575393981150',
    projectId: 'instagram-a8f7a',
    storageBucket: 'instagram-a8f7a.appspot.com',
    iosBundleId: 'com.example.instagramAppClone.RunnerTests',
  );
}
